version: "3.3"

services:
  database:
    container_name: database
    image: postgres:9.6.0
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD={{ cookiecutter.project_slug }}
      - POSTGRES_USER={{ cookiecutter.project_slug }}

  app:
    container_name: app
    build: .
    user: ${CURRENT_UID}
    command: gunicorn {{ cookiecutter.project_slug }}.wsgi -b 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - database
    links:
      - database
      - redis
  
  redis:
    container_name: redis
    image: redis
    
  celery:
    container_name: celery
    build: .
    command: celery -A {{ cookiecutter.project_slug }} worker --loglevel=DEBUG -P eventlet -c 100
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    environment:
      - C_FORCE_ROOT=true

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A {{ cookiecutter.project_slug }} beat --loglevel=DEBUG
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    environment:
      - C_FORCE_ROOT=true
  
  web:
    container_name: web
    image: nginx
    volumes:
      - ./contrib/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/var/www/
    ports:
      - 80:80
      - 443:443
    links:
      - app
    depends_on:
      - app
